# wallust 2.9.*
# -- global space -- #
# values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
#  * full       - Read and return the whole image pixels (more precision, slower)
#  * resized    - Resizes the image before parsing, mantaining it's aspect ratio
#  * wal        - Uses image magick `convert` to generate the colors, like pywal
#  * thumb      - Faster algo hardcoded to 512x512 (no ratio respected)
#  * fastresize - A much faster resize algo that uses SIMD. For some reason it
#                  fails on some images where `resized` doesn't, for this reason
#                  it does not *replace* but rather it's a new option.
backend = "resized"

# What color space to use to produce and select the most prominent colors:
#  * lab      - Uses Cie L*a*b color space
#  * labmixed - Variant of `lab` that mixes the colors gathered, if not enough
#                colors it fallbacks to usual lab (not recommended in small images)
#  * labfast  - Variant of `lab` that avoids floating arithmetic, thus, faster
#                operations but not that much precise result. Images that work on
#                lab/labmixed could not have "enough colors" for labfast.
color_space = "lab"

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
threshold = 15

# NOTE: All filters will fill 16 colors (from color0 to color15), 16 color
#       variations are the 'ilusion' of more colors by opaquing color1 to color5.
# Use the most prominent colors in a way that makes sense, a scheme:
#  * dark        - 8 dark colors, dark background and light contrast
#  * dark16      - Same as `dark` but uses the 16 colors trick
#  * harddark    - Same as `dark` with hard hue colors
#  * harddark16  - Harddark with 16 color variation
#  * light       - Light bg, dark fg
#  * light16     - Same as `light` but uses the 16 color trick
#  * softdark    - Variant of softlight, uses the lightest colors and a dark
#                   background (could be interpreted as `dark` inversed)
#  * softdark16  - softdark with 16 color variation
#  * softlight   - Light with soft pastel colors, counterpart of `harddark`
#  * softlight16 - softlight with 16 color variation
palette = "softdark16"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enables when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
saturation = 15

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
waybar.src = "colors-waybar.css"
waybar.dst = "~/.cache/wallust/colors-waybar.css"
waybar.pywal = true

kitty.src = "colors-kitty.conf"
kitty.dst = "~/.cache/wallust/colors-kitty.conf"
kitty.pywal = true

hyprland.src = "colors-hyprland.conf"
hyprland.dst = "~/.cache/wallust/colors-hyprland.conf"
hyprland.pywal = false

# neopywal.src = "colors-neopywal.vim"
# neopywal.dst = "~/.cache/wallust/colors_neopywal.vim"
# neopywal.pywal = false

discord.src = "discord-wallust.css"
discord.dst = "/home/smooch/.config/vesktop/themes/wallust.css"
discord.pywal = false

base46.src = "colors-base46.lua"
base46.dst = "/home/smooch/.config/nvim/lua/themes/wallust.lua"
base46.pywal = false

chadwal.src = "chadwal.lua"
chadwal.dst = "/home/smooch/.config/nvim/lua/themes/chadwal.lua"
chadwal.pywal = false

dunst.src = "colors-dunst.conf"
dunst.dst = "/home/smooch/.config/dunst/dunstrc.d/50-wallust-colors.conf"
dunst.pywal = false
